---
- name: provision
  hosts: all
  become: yes
  tasks:
    - name: install apache server on ubuntu
      apt:
        name: apache2
        state: present
      when:
        ansible_distribution == "Ubuntu"
    - name: install nginx server on centos
      yum:
        name: nginx
        state: present
      when:
        ansible_distribution == "CentOS"
