---
- name: provision
  hosts: all
  become: yes
  tasks:
    - name: install ntp server on ubunty
      apt:
        name: ntp
        state: present
      when:
        ansible_distribution == "Ubuntu"
    - name: install ntp server on centos
      yum:
        name: ntp
        state: present
      when:
        ansible_distribution == "Centos"
