---
- name: setup a webserver
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
    - name: start and enable apache2
      service: 
        name: apache2
        state: started
        enabled: yes
    - name: copy index.html to target dir
      copy:
        src: index.html
        dest: /var/www/html/index.html
- name: setup a DB server
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: mariadb-server
        state: present
    - name: start and enable MySQL
      service:
        name: mariadb
        state: started
        enabled: yes
