---
- name: provision server with loops and decisions
  hosts: all
  become: yes
  tasks:
    - name: Install NTP server on Ubuntu nodes
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when:
        ansible_distribution == "Ubuntu"
      loop:
        - chrony
        - wget
        - zip
        - unzip
        - curl
    - name: Install NTP on CentOS nodes
      yum:
        name: "{{item}}"
        state: present
      when:
        ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - zip
        - unzip
        - curl
    - name: Start and enable chrony on ubuntu nodes
      service:
        name: chronyd
        state: started
        enabled: yes
      when:
        ansible_distribution == "Ubuntu"
    - name: Start and enable chrony on CentOS nodes
      service:
        name: chronyd
        state: started
        enabled: yes
      when:
        ansible_distribution == "CentOS"
    - name: create a new usergroup
      group:
        name: testgrp1
        state: present
    - name: add users to the group
      user:
        name: "{{item}}"
        state: present
        groups: testgrp1
      loop:
        - test1
        - test2
        - test3
        