---
- name: create webserver
  hosts: websrvgrp
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
- name: create dbserver
  hosts: dbsrvgrp
  become: yes
  vars:
    dbname: testdb2
    dbusr: dev1
    dbusrpass: Test@123
  tasks:
    - debug:
      var: dbname
    - debug:
      msg: "dbname is: {{dbname}}"
    - name: install mariadb
      apt:
        name: mariadb-server
        state: present
    - name: install pymysql
      apt:
        name: python3-pymysql
        state: present
    - name: start and enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: create db
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{dbname}}"
        state: present
    - name: create db user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name:"{{dbusr}}"
        password: "{{dbusrpass}}"
        priv: '*.*:ALL'
        state: present