---
- name: create webserver
  hosts: websrvgrp
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
- name: create dbserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: install mariadb
      apt:
        name: mariadb-server
        state: present
    - name: install pymysql
      apt:
        name: python3-pymysql
        state: present
    - name: start and enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: create db
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: 
        state: present
    - name: create db user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name:
        password:
        priv: '*.*:ALL'
        state: present